/*
 * generated by Xtext 2.13.0
 */
package org.sbelang.dsl.generator

import org.eclipse.xtext.generator.AbstractGenerator

/**
 * Base class for SBE generators
 */
abstract class SbeLangDslBaseGenerator extends AbstractGenerator {
    protected val String LITTLE_ENDIAN_BYTE_ORDER = "littleEndian"
    protected val String OPTIONAL_PRESENCE_MODIFIER = "?"

    protected val char CHAR_LITERAL_DELIMITER = '\''
}
