/*
 * generated by Xtext 2.13.0
 */
package org.sbelang.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SbeLangDslStandaloneSetup extends SbeLangDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SbeLangDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
